[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/byd.json"
  to = "/.netlify/functions/byd"
  status = 200

[[redirects]]
  from = "/api/byd.json"
  to = "/.netlify/functions/byd"
  status = 200